In [5]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a = a.reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
b = np.arange(9)
b[b%2 == 1] = -1
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [12]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
np.where((x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)


(array([0]),)

In [18]:
a= np.arange(100).reshape(5,-1)
print(a[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [20]:
a = np.random.randint(30, 41, size = (10))
a

array([34, 32, 34, 38, 37, 32, 31, 35, 37, 33])

In [36]:
A = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 10)])
B = np.array([(7, 8, 10) ,(4, 5, 6), (1, 2, 3)])
C = A+B
E = A-B
print(C)
print(E)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [37]:
print(np.sum(A))
print(np.sum(B, axis=0))
print(np.sum(C, axis=1))

46
[12 15 19]
[31 30 31]


In [38]:
D = A@B
D

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [40]:
E = np.sort(C)
E

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [41]:
E = E.transpose()
E

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])

In [44]:
import csv
with open("/home/student/Desktop/data.csv", 'rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

[]
['Programming language', ' Designed by', ' Appeared', ' Extension']
['Python', ' Guido van Rossum', ' 1991', ' .py']
['Java', ' James Gosling', ' 1995', ' .java']
['C++', ' Bjarne Stroustrup', ' 1983', ' .cpp']
[]


In [45]:
import pandas
result = pandas.read_csv("/home/student/Desktop/data.csv")
print(result)

  Programming language         Designed by   Appeared  Extension
0               Python    Guido van Rossum       1991        .py
1                 Java       James Gosling       1995      .java
2                  C++   Bjarne Stroustrup       1983       .cpp
